import { About, AboutMe, AvatarExample, AvatarQuiz, Footer, IntroBlock, Method, ToolDescription, WhoAreAvatars } from "@@/components/layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Аватары</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <IntroBlock />
      <About />
      <AvatarQuiz />
      <WhoAreAvatars />
      <ToolDescription />
      <Method />
      <Footer />
      <AvatarExample />
      <AboutMe />
    </>
  );
}
